name: solarsim
description: "A solar PV system simulation application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^10.1.0
  intl: ^0.18.1
  uuid: ^3.0.7
  fl_chart: ^0.63.0
  vector_math: ^2.1.4
  shared_preferences: ^2.2.0
  flutter_map: ^6.0.0  # Add this
  latlong2: ^0.9.0     # Add this
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/